#Vaadin Copilot Integration Runtime Properties
#Thu Oct 08 14:14:27 CST 2026
endpoint=http\://127.0.0.1\:51325/vaadin/copilot-a432709c-601f-450e-8606-9eb199842b95
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
